version: '3.9'
services:
  db:
    volumes:
      - ./pg/postgres_data:/var/lib/postgresql

  django:
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      target: prod
    volumes:
      - ../django_project:/home/web/django_project
      - ./volumes/static:/home/web/static

  worker:
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
    volumes:
      - ../django_project:/home/web/django_project
      - ./volumes/static:/home/web/static
      - ./volumes/media:/home/web/media

  nginx:
    volumes:
      - ./nginx/sites-enabled:/etc/nginx/conf.d:ro
      - ./volumes/static:/home/web/static
    ports:
      - "${HTTP_PORT:-8888}:80"
    links:
      - django

  webpack:
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      target: dev
    image: kartoza/${COMPOSE_PROJECT_NAME:-django_project}_dev
    volumes:
      - ../django_project:/home/web/django_project
      - ./volumes/media:/home/web/media
    working_dir: /home/web/django_project/geohosting
    command: sh -c "npm install && npm run serve"
    entrypoint: [ ]
    ports:
      - "9000:9000"

  dev:
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      target: dev
    image: kartoza/${COMPOSE_PROJECT_NAME:-django_project}_dev
    volumes:
      - ../django_project:/home/web/django_project
    environment:
      # editable in .env
      - DATABASE_NAME=${DATABASE_NAME:-django}
      - DATABASE_USERNAME=${DATABASE_USERNAME:-docker}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-docker}
      - DATABASE_HOST=${DATABASE_HOST:-db}
      - DJANGO_SETTINGS_MODULE=core.settings.dev

      # Email where alters should be sent. This will be used by let's encrypt and as the django admin email.
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@example.com}
      -
      - ERPNEXT_API_KEY=${ERPNEXT_API_KEY:-erpnext_api_key}
      - ERPNEXT_API_SECRET=${ERPNEXT_API_SECRET:-erpnext_api_secret}
      - ERPNEXT_BASE_URL=${ERPNEXT_BASE_URL:-erpnext_base_url}
      -
      - SECRET_KEY=SECRET_KEY

      # REDIS CONFIG
      - REDIS_HOST=redis
      - REDIS_PASSWORD=redis_password
    ports:
      # for django test server
      - "9200:8080"
      # for ssh
      - "9201:22"
    links:
      - db
      - redis
      - worker
      - webpack
    entrypoint: [ ]
