version: '3.9'

volumes:
  database:

x-common-django:
  &default-common-django
  image: kartoza/${COMPOSE_PROJECT_NAME:-django_project}:${DJANGO_TAG:-1.0.0}
  env_file:
    - .env
  volumes:
    - static-data:/home/web/static
  restart: on-failure

services:
  redis:
    image: bitnami/redis:7.0.2
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis_password}

  db:
    image: kartoza/postgis:16-3.4
    volumes:
      - database:/opt/postgres/data
    environment:
      - PGDATA=/opt/postgres/data
      - POSTGRES_DBNAME=${DATABASE_NAME:-django}
      - POSTGRES_USER=${DATABASE_USERNAME:-docker}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-docker}

  django:
    <<: *default-common-django
    command: 'uwsgi --ini /uwsgi.conf'
    links:
      - db
      - worker

  worker:
    <<: *default-common-django
    entrypoint: [ ]
    command: 'celery -A core worker --beat -l info  --scheduler django_celery_beat.schedulers:DatabaseScheduler'
    links:
      - db
      - redis

  nginx:
    image: nginx
    hostname: nginx
    links:
      - django
